services:
  postgres:
    image: postgres:latest
    container_name: oeplan-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oeplan
    ports:
      - "5432:5432"