name: "Build, Publish and Release"

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]'

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  build-publish-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up latest git tag
        run: |
          RAW_TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${RAW_TAG#*@}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version: $VERSION"

      - name: Set up container name
        run: echo "CONTAINER_NAME=${REPOSITORY,,}" >> $GITHUB_ENV
        env:
          REPOSITORY: '${{ github.repository }}'

      ## Build docker
      - name: Docker build
        run: |
          docker build -t ghcr.io/${{ env.CONTAINER_NAME }}:latest .
          docker build -t ghcr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }} .

      # Push to GHCR (GitHub Container Registry)

      - name: GitHub (GHCR) login
        run: echo $GHCR_TOKEN | docker login ghcr.io -u LucJosin --password-stdin

      - name: GitHub (GHCR) push
        run: |
          docker push ghcr.io/${{ env.CONTAINER_NAME }}:latest
          docker push ghcr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }}
